// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/login","layout":false,"id":"1"},"2":{"path":"/","redirect":"/dashboard","parentId":"ant-design-pro-layout","id":"2"},"3":{"path":"/dashboard","name":"工作台","icon":"dashboard","parentId":"ant-design-pro-layout","id":"3"},"4":{"path":"/system","name":"系统管理","icon":"setting","parentId":"ant-design-pro-layout","id":"4"},"5":{"path":"/system/user","name":"用户管理","parentId":"4","id":"5"},"6":{"path":"/system/role","name":"角色管理","parentId":"4","id":"6"},"7":{"path":"/system/menu","name":"菜单管理","parentId":"4","id":"7"},"ant-design-pro-layout":{"id":"ant-design-pro-layout","path":"/","isLayout":true}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import(/* webpackChunkName: "p__Login__index" */'@/pages/Login/index.tsx')),
'2': React.lazy(() => import('./EmptyRoute')),
'3': React.lazy(() => import(/* webpackChunkName: "p__Dashboard__index" */'@/pages/Dashboard/index.tsx')),
'4': React.lazy(() => import('./EmptyRoute')),
'5': React.lazy(() => import(/* webpackChunkName: "p__System__User__index" */'@/pages/System/User/index.tsx')),
'6': React.lazy(() => import(/* webpackChunkName: "p__System__Role__index" */'@/pages/System/Role/index.tsx')),
'7': React.lazy(() => import(/* webpackChunkName: "p__System__Menu__index" */'@/pages/System/Menu/index.tsx')),
'ant-design-pro-layout': React.lazy(() => import(/* webpackChunkName: "umi__plugin-layout__Layout" */'/Users/ysy/Desktop/ai_proj/saas-mall/ui/admin/src/.umi/plugin-layout/Layout.tsx')),
},
  };
}
