// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import DashboardOutlined from '/Users/ysy/Desktop/ai_proj/saas-mall/ui/admin/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/DashboardOutlined';
import SettingOutlined from '/Users/ysy/Desktop/ai_proj/saas-mall/ui/admin/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/SettingOutlined';
export default { DashboardOutlined, SettingOutlined };
